[Rainmeter]
Update=500
AccurateText=1
DynamicWindowSize=1

[Variables]
PluginName=MediaPlayer.dll

; LCD 문자색
LCDText=24,55,55,255

; 메인 LCD 폰트
MainFont=Long Pixel-7


; ==================================================
; MEDIA
; ==================================================

[mTitle]
Measure=Plugin
Plugin=#PluginName#
PlayerType=Title
Substitute="":"No player active"

[mPosition]
Measure=Plugin
Plugin=#PluginName#
PlayerType=Position

[mState]
Measure=Plugin
Plugin=#PluginName#
PlayerType=State


; ==================================================
; DEVICE BODY
; ==================================================

[PlayerBody]
Meter=Image
ImageName=#@#Images\player_body.png
X=0
Y=0
W=300
H=100
PreserveAspectRatio=1


; ==================================================
; TITLE
; 2px 왼쪽 이동
; ==================================================

[Title]
Meter=String
MeasureName=mTitle
X=69
Y=33
W=150
H=26
FontFace=#MainFont#
FontSize=8.7
FontColor=#LCDText#
AntiAlias=0
ClipString=1

[TitleThickness]
Meter=String
MeasureName=mTitle
X=70
Y=33
W=149
H=26
FontFace=#MainFont#
FontSize=8.7
FontColor=#LCDText#
AntiAlias=0
ClipString=1


; ==================================================
; BATTERY ICON
; 오른쪽으로 2px 이동
; ==================================================

[BatteryOutline]
Meter=Shape
Shape=Rectangle 214,35,12,7,1 | Fill Color 0,0,0,0 | StrokeWidth 1 | Stroke Color #LCDText#

[BatteryTip]
Meter=Shape
Shape=Rectangle 226,37,2,3 | Fill Color #LCDText# | StrokeWidth 0

[Battery1]
Meter=Shape
Shape=Rectangle 216,37,2,3 | Fill Color #LCDText# | StrokeWidth 0

[Battery2]
Meter=Shape
Shape=Rectangle 219,37,2,3 | Fill Color #LCDText# | StrokeWidth 0

[Battery3]
Meter=Shape
Shape=Rectangle 222,37,2,3 | Fill Color #LCDText# | StrokeWidth 0


; ==================================================
; PLAY SYMBOL
; 문자 > 대신 작은 삼각형
; ==================================================

[PlaySymbol]
Meter=Shape
Shape=Path PlayTriangle | Fill Color #LCDText# | StrokeWidth 0
PlayTriangle=72,54 | LineTo 72,60 | LineTo 77,57 | ClosePath 1


; ==================================================
; ELAPSED TIME
; 2px 아래로 이동
; ==================================================

; ==================================================
; ELAPSED TIME
; ==================================================

[Position]
Meter=String
MeasureName=mPosition
X=80
Y=51
FontFace=#MainFont#
FontSize=5
FontColor=#LCDText#
AntiAlias=0

InlineSetting=CharacterSpacing | 0.6 | 0.6이거 두께나 크기 늘리는법


; ==================================================
; EQUALIZER
; 모두 같은 길이
; ==================================================

[EQ1]
Meter=Shape
Shape=Rectangle 209,52,2,10,0 | Fill Color #LCDText# | StrokeWidth 0

[EQ2]
Meter=Shape
Shape=Rectangle 213,52,2,10,0 | Fill Color #LCDText# | StrokeWidth 0

[EQ3]
Meter=Shape
Shape=Rectangle 217,52,2,10,0 | Fill Color #LCDText# | StrokeWidth 0

[EQ4]
Meter=Shape
Shape=Rectangle 221,52,2,10,0 | Fill Color #LCDText# | StrokeWidth 0

[EQ5]
Meter=Shape
Shape=Rectangle 225,52,2,10,0 | Fill Color #LCDText# | StrokeWidth 0

; ==================================================
; INVISIBLE CONTROLS
; ==================================================

[PreviousButton]
Meter=Shape
Shape=Rectangle 15,30,18,35 | Fill Color 0,0,0,1 | StrokeWidth 0
LeftMouseUpAction=[!CommandMeasure "mState" "Previous"]

[PlayPauseButton]
Meter=Shape
Shape=Rectangle 35,30,20,35 | Fill Color 0,0,0,1 | StrokeWidth 0
LeftMouseUpAction=[!CommandMeasure "mState" "PlayPause"]

[NextButton]
Meter=Shape
Shape=Rectangle 57,30,18,35 | Fill Color 0,0,0,1 | StrokeWidth 0
LeftMouseUpAction=[!CommandMeasure "mState" "Next"]